services:
  backend-dev:
    build:
      context: .
      dockerfile: ./backend/DockerFile.backend
      target: dev
    volumes:
      - ./backend:/app
    ports: 
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/mern-dev
    depends_on:
      - db    

  frontend-dev:
    build:
      context: .
      dockerfile: front-end/Dockerfile.frontend
      target: dev
    volumes:
      - ./frontend:/app
    ports: 
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3000

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mern_db:/data/db  

volumes:
  mern_db:
