# stages 
FROM node:22-alpine as dev

#Define working directory in container
WORKDIR /app

# Copy package.json and package-lock.json to container

COPY backend/package.json ./
RUN npm install

# Copy all files to container

COPY backend/ .


CMD ["npm","run","dev"]


#