# stages 
FROM node:22-alpine as build

#Define working directory in container
WORKDIR /app

# Copy package.json and package-lock.json to container

COPY frontend/package.json ./
RUN npm install

# Copy all files to container

COPY frontend/ .

RUN npm run build


# prod stages
FROM nginx:alpine as prod

COPY --from=build /app/build /usr/share/nginx/html

CMD["nginx", "-g", "daemon off;"]

#